version: '3.8'

services:
  influxdb2:
    image: influxdb:2.7
    container_name: influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123!
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-nflx}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-default}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    networks:
      - telemetry_network

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      # Enable admin login with default credentials
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123!}
      # Keep GitHub OAuth as additional option
      - GF_AUTH_GITHUB_ENABLED=${GITHUB_OAUTH_ENABLED:-true}
      - GF_AUTH_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GF_AUTH_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GF_AUTH_GITHUB_SCOPES=${GITHUB_SCOPES:-user}
      - GF_AUTH_GITHUB_ALLOW_SIGN_UP=${GITHUB_ALLOW_SIGN_UP:-true}
      - GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS=${GITHUB_ALLOWED_ORGANIZATIONS:-}
      - GF_AUTH_GITHUB_TEAM_IDS=${GITHUB_TEAM_IDS:-}
      # Note: MapGL plugin not available, using built-in geomap instead
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - telemetry_network
    depends_on:
      - influxdb2

  telemetry:
    build: ./telemetry
    container_name: telemetry
    environment:
      - INFLUX_URL=http://influxdb2:8086
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUX_BUCKET=${INFLUXDB_BUCKET:-default}
      - INFLUX_ORG=${INFLUXDB_ORG:-nflx}
      - DESTINATIONS=${NETWORK_DESTINATIONS:-google.com,github.com,stackoverflow.com}
      - COLLECT_INTERVAL=${TELEMETRY_COLLECT_INTERVAL:-60}
    depends_on:
      - influxdb2
    networks:
      - telemetry_network

volumes:
  influxdb2_data:
  influxdb2_config:
  grafana_data:

networks:
  telemetry_network:
    driver: bridge